In [1]:
import os
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv("../data/derived/CarCrashData-Cleaned.csv")
data.datetime = pd.to_datetime(data.datetime, format="%Y/%m/%d %H:%M:%S")
data.head()

,datetime,day_of_week,lga,latitude,longitude,type,road_class,is_hit_and_run,light_condition,police_attended,...,total_non_injury,total_male,total_female,total_bicyclist,totaL_passenger,total_driver,total_pedestrian,total_pillion,total_motorist,total_unknown
0,2015-07-01 01:37:00,Wednesday,Wyndham,-37.868424,144.733170,Overturned (no collision),Arterial Other,False,Dark (lights on),True,...,0,1,0,0,0,0,0,0,1,0
1,2015-07-01 03:05:00,Wednesday,Monash,-37.893493,145.093413,Vehicle,Arterial Highway,False,Dark (lights on),True,...,2,2,0,0,1,2,0,0,1,0
2,2015-07-01 04:10:00,Wednesday,Yarra Ranges,-37.897932,145.357961,Animal,Arterial Other,False,Dark (no lights),False,...,0,1,0,0,0,0,0,0,1,0
3,2015-07-01 04:30:00,Wednesday,Geelong,-38.150540,144.581600,Vehicle,NaN,False,Dark (no lights),True,...,1,1,2,0,0,1,2,0,0,0
4,2015-07-01 04:30:00,Wednesday,Casey,-37.996330,145.269155,Pedestrian,Freeway,False,Dark (lights on),True,...,1,2,0,0,0,1,1,0,0,0

In [8]:
data["year"] = data.datetime.dt.year
data["month"] = data.datetime.dt.month
data["day"] = data.datetime.dt.day
data["hour"] = data.datetime.dt.hour
data["minute"] = data.datetime.dt.minute
data["year"] = data.datetime.dt.year

In [10]:
data.to_csv("../data/derived/CarCrashData-Temporal.csv", index=False)

In [13]:
data.is_alcohol_time

0        True
1        True
2        True
3        True
4        True
         ...
75202    True
75203    True
75204    True
75205    True
75206    True
Name: is_alcohol_time, Length: 75207, dtype: bool